import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react';
import { AlertCircle, ChevronDown, ChevronLeft, ChevronRight, Edit3, Loader2, Plus, Search, UserRound, X } from 'lucide-react';
import { useAuth } from '../auth/AuthContext';
import { employeeService, type EmployeeCreateInput, type EmployeeLookups } from '../services/employee.service';
import { getErrorMessage } from '../lib/errors';
import type { EmployeeProfileRow, EmploymentStatus } from '../types/database';

const inputStyle = { background: '#0d1b2e', border: '1px solid #1e3a5a', color: '#f0f6ff', borderRadius: 8, padding: '8px 12px', width: '100%', fontSize: 13, outline: 'none' } as const;
const statuses: Array<EmploymentStatus | ''> = ['', 'active', 'inactive', 'on_leave', 'terminated'];
const emptyForm: EmployeeCreateInput = { organization_id: '', employee_code: '', iqama_number: '', full_name: '', mobile_number: '', branch_id: '', department_id: '', job_title: '', manager_user_id: null, joining_date: '', employment_status: 'active' };

function Select({ value, onChange, children }: { value: string; onChange: (value: string) => void; children: ReactNode }) {
  return <div className="relative"><select value={value} onChange={event => onChange(event.target.value)} style={{ ...inputStyle, appearance: 'none' }}>{children}</select><ChevronDown size={13} className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none" style={{ color: '#4b6a8a' }} /></div>;
}
function Status({ status }: { status: EmploymentStatus }) { const color = status === 'active' ? '#10b981' : status === 'on_leave' ? '#f59e0b' : '#94a3b8'; return <span className="text-xs px-2 py-1 rounded-lg capitalize" style={{ color, background: `${color}18` }}>{status.replace(/_/g, ' ')}</span>; }

function EmployeeModal({ employee, lookups, organizationId, onClose, onSaved }: { employee: EmployeeProfileRow | null; lookups: EmployeeLookups; organizationId: string; onClose: () => void; onSaved: (employee: EmployeeProfileRow) => void }) {
  const [form, setForm] = useState<EmployeeCreateInput>(() => employee ? { organization_id: employee.organization_id, employee_code: employee.employee_code, iqama_number: employee.iqama_number, full_name: employee.full_name, mobile_number: employee.mobile_number, branch_id: employee.branch_id, department_id: employee.department_id, job_title: employee.job_title, manager_user_id: employee.manager_user_id, joining_date: employee.joining_date, employment_status: employee.employment_status } : { ...emptyForm, organization_id: organizationId });
  const [shiftId, setShiftId] = useState('');
  const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const update = (key: keyof EmployeeCreateInput, value: string | null) => setForm(current => ({ ...current, [key]: value }));
  const save = async () => {
    if (!form.full_name.trim() || !form.employee_code.trim() || !form.iqama_number.trim() || !form.branch_id || !form.department_id) { setError('Name, employee ID, Iqama, site, and department are required.'); return; }
    if (!/^\d{10}$/.test(form.iqama_number)) { setError('Iqama number must contain 10 digits.'); return; }
    setSaving(true); setError('');
    try { const saved = employee ? await employeeService.update(employee.id, form as never) : await employeeService.create(form); if (shiftId) await employeeService.assignShift({ organization_id: organizationId, employee_id: saved.id, shift_id: shiftId }); onSaved(saved); onClose(); } catch (caught) { setError(getErrorMessage(caught)); } finally { setSaving(false); }
  };
  const field = (label: string, content: ReactNode) => <label className="text-xs" style={{ color: '#94a3b8' }}>{label}{content}</label>;
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{ background: 'rgba(6,13,26,0.85)', backdropFilter: 'blur(4px)' }}><div className="w-full max-w-2xl rounded-2xl overflow-hidden" style={{ background: '#0d1b2e', border: '1px solid #1e3a5a' }}>
    <div className="flex items-center justify-between px-6 py-4" style={{ borderBottom: '1px solid #1e3a5a', background: '#08111f' }}><div className="font-bold text-white text-sm">{employee ? 'Edit Employee' : 'Add New Employee'}</div><button onClick={onClose} aria-label="Close employee form" style={{ color: '#4b6a8a' }}><X size={16} /></button></div>
    <div className="p-6 grid grid-cols-2 gap-4 max-h-[70vh] overflow-y-auto">
      {field('Full name', <input style={inputStyle} value={form.full_name} onChange={event => update('full_name', event.target.value)} />)}
      {field('Employee ID', <input style={inputStyle} value={form.employee_code} onChange={event => update('employee_code', event.target.value.toUpperCase())} />)}
      {field('Iqama number', <input style={inputStyle} maxLength={10} value={form.iqama_number} onChange={event => update('iqama_number', event.target.value.replace(/\D/g, ''))} />)}
      {field('Mobile number', <input style={inputStyle} value={form.mobile_number ?? ''} onChange={event => update('mobile_number', event.target.value)} />)}
      {field('Site', <Select value={form.branch_id} onChange={value => update('branch_id', value)}><option value="">Select site…</option>{lookups.branches.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</Select>)}
      {field('Department', <Select value={form.department_id} onChange={value => update('department_id', value)}><option value="">Select department…</option>{lookups.departments.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</Select>)}
      {field('Manager', <Select value={form.manager_user_id ?? ''} onChange={value => update('manager_user_id', value || null)}><option value="">No manager</option>{lookups.managers.map(item => <option key={item.id} value={item.id}>{item.display_name}</option>)}</Select>)}
      {field('Job title', <input style={inputStyle} value={form.job_title ?? ''} onChange={event => update('job_title', event.target.value)} />)}
      {field('Assigned shift', <Select value={shiftId} onChange={setShiftId}><option value="">No shift change</option>{lookups.shifts.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</Select>)}
      {field('Joining date', <input type="date" style={inputStyle} value={form.joining_date ?? ''} onChange={event => update('joining_date', event.target.value)} />)}
      {field('Employment status', <Select value={form.employment_status ?? 'active'} onChange={value => update('employment_status', value)}>{statuses.filter(Boolean).map(item => <option key={item} value={item}>{item.replace(/_/g, ' ')}</option>)}</Select>)}
    </div>
    {error && <div className="mx-6 mb-4 rounded-xl p-3 flex gap-2 text-xs" style={{ background: 'rgba(239,68,68,0.1)', color: '#fca5a5' }} role="alert"><AlertCircle size={15} />{error}</div>}
    <div className="px-6 py-4 flex justify-end gap-3" style={{ borderTop: '1px solid #1e3a5a', background: '#08111f' }}><button onClick={onClose} className="px-4 py-2 rounded-lg text-sm" style={{ background: '#122338', color: '#94a3b8' }}>Cancel</button><button onClick={() => void save()} disabled={saving} className="px-5 py-2 rounded-lg text-sm font-semibold flex items-center gap-2" style={{ background: '#2563eb', color: '#fff', opacity: saving ? .6 : 1 }}>{saving && <Loader2 size={14} className="animate-spin" />}{employee ? 'Save changes' : 'Create employee'}</button></div>
  </div></div>;
}

export default function Employees() {
  const { activeMembership, hasAnyRole } = useAuth(); const organizationId = activeMembership?.organization_id; const canEdit = hasAnyRole(['administrator']);
  const [rows, setRows] = useState<EmployeeProfileRow[]>([]); const [lookups, setLookups] = useState<EmployeeLookups>({ branches: [], departments: [], shifts: [], managers: [] }); const [search, setSearch] = useState(''); const [status, setStatus] = useState<EmploymentStatus | ''>(''); const [branchId, setBranchId] = useState(''); const [departmentId, setDepartmentId] = useState(''); const [sortBy, setSortBy] = useState<'full_name' | 'employee_code' | 'created_at' | 'employment_status'>('full_name'); const [ascending, setAscending] = useState(true); const [page, setPage] = useState(1); const [count, setCount] = useState(0); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [selected, setSelected] = useState<EmployeeProfileRow | null>(null); const [editing, setEditing] = useState<EmployeeProfileRow | null | undefined>(undefined); const pageSize = 10;
  const load = useCallback(async () => { if (!organizationId) return; setLoading(true); setError(''); try { const [result, options] = await Promise.all([employeeService.list({ organizationId, search, status: status || undefined, branchId: branchId || undefined, departmentId: departmentId || undefined, sortBy, sortAscending: ascending, page, pageSize }), employeeService.getLookups(organizationId)]); setRows(result.rows); setCount(result.count); setLookups(options); } catch (caught) { setError(getErrorMessage(caught)); } finally { setLoading(false); } }, [organizationId, search, status, branchId, departmentId, sortBy, ascending, page]);
  useEffect(() => { void load(); }, [load]); useEffect(() => { setPage(1); }, [search, status, branchId, departmentId]);
  const branchName = useMemo(() => new Map(lookups.branches.map(item => [item.id, item.name])), [lookups.branches]); const departmentName = useMemo(() => new Map(lookups.departments.map(item => [item.id, item.name])), [lookups.departments]); const totalPages = Math.max(1, Math.ceil(count / pageSize));
  const saved = (employee: EmployeeProfileRow) => { setEditing(undefined); setSelected(employee); void load(); }; const toggleStatus = async (employee: EmployeeProfileRow) => { try { const updated = await employeeService.setStatus(employee.id, employee.employment_status === 'active' ? 'inactive' : 'active'); setSelected(updated); void load(); } catch (caught) { setError(getErrorMessage(caught)); } };
  if (!organizationId) return <div className="rounded-xl p-8 text-center" style={{ background: '#0d1b2e', border: '1px solid #1e3a5a' }}><AlertCircle className="mx-auto mb-3" style={{ color: '#f59e0b' }} /><div className="text-white font-semibold">No active organization</div><div className="text-sm mt-1" style={{ color: '#4b6a8a' }}>Your account needs an active organization assignment.</div></div>;
  return <div className="space-y-4">
    {editing !== undefined && <EmployeeModal employee={editing} lookups={lookups} organizationId={organizationId} onClose={() => setEditing(undefined)} onSaved={saved} />}
    <div className="flex items-center justify-between"><div><h1 className="text-xl font-bold text-white">Employees</h1><p className="text-sm mt-0.5" style={{ color: '#4b6a8a' }}>Manage employees, assignments, and employment status</p></div>{canEdit && <button onClick={() => setEditing(null)} className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold" style={{ background: '#2563eb', color: '#fff' }}><Plus size={15} /> Add employee</button>}</div>
    {error && <div className="rounded-xl p-3 flex gap-2 text-xs" style={{ background: 'rgba(239,68,68,0.1)', color: '#fca5a5' }} role="alert"><AlertCircle size={15} />{error}<button className="ml-auto underline" onClick={() => void load()}>Retry</button></div>}
    <div className="rounded-xl p-4 grid grid-cols-5 gap-3" style={{ background: '#0d1b2e', border: '1px solid #1e3a5a' }}><div className="relative"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2" style={{ color: '#4b6a8a' }} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search name, ID, Iqama…" style={{ ...inputStyle, paddingLeft: 34 }} /></div><Select value={branchId} onChange={setBranchId}><option value="">All sites</option>{lookups.branches.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select value={departmentId} onChange={setDepartmentId}><option value="">All departments</option>{lookups.departments.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select value={status} onChange={value => setStatus(value as EmploymentStatus | '')}><option value="">All statuses</option>{statuses.filter(Boolean).map(item => <option key={item} value={item}>{item.replace(/_/g, ' ')}</option>)}</Select><Select value={sortBy} onChange={value => setSortBy(value as typeof sortBy)}><option value="full_name">Sort: name</option><option value="employee_code">Sort: employee ID</option><option value="created_at">Sort: newest</option><option value="employment_status">Sort: status</option></Select></div>
    <div className="rounded-xl overflow-hidden" style={{ border: '1px solid #1e3a5a' }}><table className="w-full"><thead><tr style={{ background: '#122338' }}>{['Employee','Employee ID','Site / Department','Manager','Status','Actions'].map(heading => <th key={heading} className="text-left px-4 py-3 text-xs font-semibold uppercase tracking-wider" style={{ color: '#4b6a8a' }}>{heading}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={6} className="p-10 text-center"><Loader2 className="mx-auto animate-spin" style={{ color: '#3b82f6' }} /></td></tr> : rows.length === 0 ? <tr><td colSpan={6} className="p-12 text-center"><UserRound className="mx-auto mb-3" style={{ color: '#1e3a5a' }} /><div className="text-white font-semibold">No employees found</div><div className="text-xs mt-1" style={{ color: '#4b6a8a' }}>Adjust the filters or add the first employee.</div></td></tr> : rows.map(employee => <tr key={employee.id} className="border-t" style={{ borderColor: '#1e3a5a' }}><td className="px-4 py-3"><button onClick={() => setSelected(employee)} className="flex items-center gap-3 text-left"><div className="w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold text-white" style={{ background: 'linear-gradient(135deg,#2563eb,#06b6d4)' }}>{employee.full_name.split(/\s+/).map(part => part[0]).join('').slice(0, 2)}</div><div><div className="text-sm font-semibold text-white">{employee.full_name}</div><div className="text-xs" style={{ color: '#4b6a8a' }}>{employee.job_title || 'Employee'}</div></div></button></td><td className="px-4 py-3 text-xs font-mono" style={{ color: '#93c5fd' }}>{employee.employee_code}<div style={{ color: '#4b6a8a' }}>{employee.iqama_number}</div></td><td className="px-4 py-3 text-xs" style={{ color: '#94a3b8' }}>{branchName.get(employee.branch_id) || '—'}<div style={{ color: '#4b6a8a' }}>{departmentName.get(employee.department_id) || '—'}</div></td><td className="px-4 py-3 text-xs" style={{ color: '#94a3b8' }}>{lookups.managers.find(item => item.id === employee.manager_user_id)?.display_name || '—'}</td><td className="px-4 py-3"><Status status={employee.employment_status} /></td><td className="px-4 py-3"><div className="flex items-center gap-2">{canEdit && <button onClick={() => setEditing(employee)} className="p-1.5 rounded-lg" style={{ color: '#93c5fd', background: '#122338' }} title="Edit"><Edit3 size={14} /></button>}<button onClick={() => setSelected(employee)} className="p-1.5 rounded-lg" style={{ color: '#4b6a8a', background: '#122338' }} title="Details"><ChevronRight size={14} /></button></div></td></tr>)}</tbody></table></div>
    <div className="flex items-center justify-between text-xs" style={{ color: '#4b6a8a' }}><span>{count === 0 ? '0 employees' : `${(page - 1) * pageSize + 1}–${Math.min(page * pageSize, count)} of ${count}`}</span><div className="flex items-center gap-2"><button disabled={page <= 1} onClick={() => setPage(value => value - 1)} className="p-1.5 rounded-lg disabled:opacity-30" style={{ background: '#122338' }}><ChevronLeft size={14} /></button><span>Page {page} of {totalPages}</span><button disabled={page >= totalPages} onClick={() => setPage(value => value + 1)} className="p-1.5 rounded-lg disabled:opacity-30" style={{ background: '#122338' }}><ChevronRight size={14} /></button><button onClick={() => setAscending(value => !value)} className="ml-2 px-2 py-1 rounded" style={{ background: '#122338', color: '#93c5fd' }}>{ascending ? 'Ascending' : 'Descending'}</button></div></div>
    {selected && <div className="fixed inset-0 z-40 flex items-center justify-center p-4" style={{ background: 'rgba(6,13,26,0.82)' }}><div className="w-full max-w-lg rounded-2xl p-6" style={{ background: '#0d1b2e', border: '1px solid #1e3a5a' }}><div className="flex items-start justify-between"><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-xl flex items-center justify-center text-white font-bold" style={{ background: 'linear-gradient(135deg,#2563eb,#06b6d4)' }}>{selected.full_name.split(/\s+/).map(part => part[0]).join('').slice(0, 2)}</div><div><h2 className="font-bold text-white">{selected.full_name}</h2><div className="text-xs font-mono" style={{ color: '#3b82f6' }}>{selected.employee_code}</div></div></div><button onClick={() => setSelected(null)} style={{ color: '#4b6a8a' }}><X size={16} /></button></div><div className="grid grid-cols-2 gap-3 mt-6">{[['Iqama', selected.iqama_number],['Mobile', selected.mobile_number || '—'],['Site', branchName.get(selected.branch_id) || '—'],['Department', departmentName.get(selected.department_id) || '—'],['Manager', lookups.managers.find(item => item.id === selected.manager_user_id)?.display_name || '—'],['Joined', selected.joining_date || '—']].map(([label, value]) => <div key={label} className="rounded-xl p-3" style={{ background: '#122338' }}><div className="text-xs" style={{ color: '#4b6a8a' }}>{label}</div><div className="text-sm text-white mt-1">{value}</div></div>)}</div><div className="flex items-center justify-between mt-6"><Status status={selected.employment_status} /><div className="flex gap-2">{canEdit && <><button onClick={() => { setEditing(selected); setSelected(null); }} className="px-3 py-2 rounded-lg text-xs flex items-center gap-1" style={{ background: '#122338', color: '#93c5fd' }}><Edit3 size={13} /> Edit</button><button onClick={() => void toggleStatus(selected)} className="px-3 py-2 rounded-lg text-xs" style={{ background: selected.employment_status === 'active' ? 'rgba(239,68,68,.12)' : 'rgba(16,185,129,.12)', color: selected.employment_status === 'active' ? '#fca5a5' : '#6ee7b7' }}>{selected.employment_status === 'active' ? 'Deactivate' : 'Activate'}</button></>}</div></div></div></div>}
  </div>;
}
