-- Compatibility pointer only. The deployable database source of truth is:
-- ../supabase/migrations/20260928200408_rls_hardening.sql
--
-- Keep schema changes in the repository-root supabase/migrations directory so
-- the web and Android applications always deploy the same backend history.
