-- Historical migration retained as a no-op for fresh/replayed environments.
-- Auth users and credentials must never be created from migrations. Use the
-- trusted provision-employee Edge Function and Supabase Auth Admin API.
