-- Historical migration retained as a no-op to preserve migration history parity
-- with the production project. The mailroom employee roster is real operational
-- data (names + Iqama numbers), not schema, so it must not be re-seeded on every
-- `supabase db push`. The idempotent provisioning script now lives at
-- ../seed/mailroom_employees.sql and is applied deliberately, not automatically.
--
-- Production already contains these rows from the original run of this migration;
-- converting the body to a no-op leaves that data untouched.
